# Problem 2
# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.


UPPER_LIMIT = 4000000


def main():
    assert solution_1() == 4613732


def solution_1():
    first_term = 1
    second_term = 0
    solution_sum = 0
    while first_term < UPPER_LIMIT:
        if not first_term % 2:
            solution_sum += first_term
        first_term = second_term + first_term
        second_term = first_term - second_term
    return solution_sum


if __name__ == "__main__":
    main()
